Разметка главной
htmlacademy-adaptive/1390101-cat-energy-24 pull request #2
Opened 2021-11-28 19:07 UTC by Kris-js

2021-11-28 20:41 UTC, wrgraff requested changes
Для начала неплохо. Логику кажется соблюдать получается, но есть некоторые ошибки именно в нейминге.

2021-11-28 20:41 UTC, wrgraff commented on Readme.md
> +* Наставник: [Артур Трифонов](https://htmlacademy.ru/profile/wrgraff).
Как так случилось, что эта правка вновь попала в пул-реквест?
Напиши мне пожалуйста процесс, по которому ты приступала к новому заданию.

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +      <img class="page-header__logo-image" src="" width="33" height="38" alt="Кэт Энерджи">
Можно и не писать разный `alt`, а оставить в одной из картинок его пустым (можно так же добавить атрибут `aria-hidden="true"` чтобы картинка не всплывала в инструментах доступности.

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +      <img class="page-header__logo-text" src="" width="101" height="18" alt="CAT ENERGY">
Лучше пистаь по обычному:
```suggestion
      <img class="page-header__logo-text" src="" width="101" height="18" alt="Cat Energy">
```

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +            <a>Каталог продукции</a>
А у ссылок на каталог и подбор программы разве нет адреса?
Мы эти страницы даже сделаем, они есть в макете. Нам нужно поставить их адреса, а даже не заглушки.

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +            <a>Главная</a>
Не стоит ли поставить какой-то класс для оформления ссылок?

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +        <h1 class="page-main__title">Функциональное питание для котов</h1>
А почему мы снова внутри уже блока `slogan` создаем элементы блока `page-main`?
В этом конечно есть определенный смысл в некоторых случаях, но далеко не всегда. И мне бы хотелось понять -- намеренно ли это сделано, и если да, то зачем.

Я не вижу в этом большой выгоды, поэтому требуется пояснение

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +          <h2 class="visually-hidden">Предложения Кэт Энерджи</h2>
Ой!
Как это заголовок отправился внутрь списка?
В списках допустимы только элементы списка.

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +            <img class="benefits__image" src="" alt="Кот" width="50" height="50">
Этак картинка не попадает под контентную.
Чтобы картинку поставить в контент у нас есть 2 повода:
1. она несет сама по себе уникальную информацию (изображение упаковки товара, карта проезда и прочее)
2. это иконка, которой нужно будет при наведении и/или нажатии изменять цвет.

Здесь у нас ни то, ни другое. Следовательно, картинку можно вставить исключительно средствами CSS

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +              </svg>
Эта иконка тоже добавляется через CSS

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +              <svg class="benefits__link--icon" aria-hidden="true" focusable="false" width="24" height="12">
Модификатор применен без элемента.
Модификатор — это такая штука, которая берет готовый элемент или блок, и что-то в нем меняет. Например, у нас есть блок `button`. Он по умолчанию имеет какой-то размер, а нам нужен такой же, только побольше: там шрифт чуть крупнее и отступы. Мы создаем модификатор, который добавит именно эти стили: `button--large`.
Тогда получается, обычный элемент будет выглядеть так:
```html
<button class="button" type="button">Кнопка</button>
```

А если нам нужна будет кнопка побольше, то мы добавим модификатор к ней же, вторым классом:
```html
<button class="button button--large" type="button">Кнопка</button>
```

В самом по себе модификаторе смысла нет, он применяется к уже существующему блоку или элементу. Он не самостоятелен и это всегда не первый и не единственный класс.

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +            <img class="advantages__image" src="">
Несут ли эти картинки какую-то особую информацию?
Как их привязать к элементам, если нужно их ставить через стили?

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +        <ul class="advantages__list">
Выглядит как весьма пронумерованный список. Логично использовать `<ol>`

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +        <ul class="example__list">
Для этого списка хорошо бы подошел список с парными пунктами `<dl>`

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +            <span class="example__description--statistics">5 КГ</span>
Снова модификатор без элемента.
Такие ошибки есть и далее, они хорошо видны если проверить код [этим инструментом](https://yoksel.github.io/html-tree/).
Проверь разметку с его помощью.

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +            <p class="example__description example-text">затрачено времени</p>
Не совсем понятно: зачем здесь целый отдельный блок `example-text`?
Ради оформления одной только подписи это немного перебор =)

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +          <svg class="page-footer__logo--image footer__logo" aria-hidden="true" focusable="false" width="128"
`footer__logo` — это получается элемент блока `footer`.
А такого блока нет, есть только `page-footer`

2021-11-28 20:41 UTC, wrgraff commented on source/index.html
> +        <ul class="social__list">
А где задан блок `social`?
Элементы оказались без блока

2021-11-29 13:31 UTC, Kris-js commented on source/index.html
> +      <img class="page-header__logo-image" src="" width="33" height="38" alt="Кэт Энерджи">
Добавила

2021-11-29 13:33 UTC, Kris-js commented on source/index.html
> +      <img class="page-header__logo-text" src="" width="101" height="18" alt="CAT ENERGY">
Оставила пустым, но поняла, что лучше не использовать капс лок

2021-11-29 13:41 UTC, Kris-js commented on source/index.html
> +            <a>Каталог продукции</a>
Ага не посмотрела. Вставила, пока заглушки, файлов нет)

2021-11-29 13:41 UTC, Kris-js commented on source/index.html
> +            <a>Главная</a>
Поставила

2021-11-29 13:49 UTC, Kris-js commented on source/index.html
> +        <h1 class="page-main__title">Функциональное питание для котов</h1>
поправила) Сделано не намеренно. Сначала задала page-main и разметку, а потом уже обернула в секцию

2021-11-29 14:02 UTC, Kris-js commented on source/index.html
> +          <h2 class="visually-hidden">Предложения Кэт Энерджи</h2>
Поставила перед списком. Подумалось, что если заголовок скрытый, то можно засунуть в список.)

2021-11-29 14:08 UTC, Kris-js commented on source/index.html
> +              </svg>
ОК, убрала

2021-11-29 14:19 UTC, Kris-js commented on source/index.html
> +            <img class="advantages__image" src="">
Убрала

2021-11-29 19:10 UTC, Kris-js commented on source/index.html
> +        <ul class="advantages__list">
Согласна,  на планшетной версии уже виден пронумерованный список.

2021-11-29 19:22 UTC, Kris-js commented on source/index.html
> +        <ul class="example__list">
исправила

2021-11-30 18:48 UTC, Kris-js commented on source/index.html
> +            <p class="example__description example-text">затрачено времени</p>
убрала

2021-11-30 19:03 UTC, Kris-js commented on source/index.html
> +        <ul class="social__list">
исправила

2021-11-30 19:03 UTC, Kris-js commented on source/index.html
> +          <svg class="page-footer__logo--image footer__logo" aria-hidden="true" focusable="false" width="128"
исправила

2021-11-30 21:57 UTC, wrgraff requested changes

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +      <img class="page-header__logo-image" src="" aria-hidden="true" width="33" height="38" alt="Кэт Энерджи">
Но зачем же ты скрыла обе картинки?
Было 2, которые друг другу мешают. Теперь нет ни одной (

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +<body class="page-body">
Зачем элемент сменился на блок?

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +          <li class="site-list__item site-list__item-active">
Был элемент и его модификатор, чтобы выделить активную страницу среди таких же элементов.
Теперь — 2 независимых элемента на одном теге =(

Было правильно, стало неправильно

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +            <a class="site-list__item-link" href="#">Главная</a>
Есть 2 способа реализации:
У главной либо нет ссылки, так как мы на ней, либо она есть, но тогда это должна быть не заглушка, а ссылка на главную.

Заглушки тут быть не может

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +            <a class="site-list__item-link" href="#">Каталог продукции</a>
Мы уже знаем, что 2 страницы будут `catalog.html` и `form.html`.
Нужно их и поставить

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +            <a class="site-list__item-link" href="#">Подбор программы</a>
В данной ситуации `item-link` — это такой скрытый элемент элемента. Мы как бы напрямую так не делаем, но все равно к `item` привязываем имя.
Будь проще. Блок и элемент. Блок у нас `site-list`, элемент — `link`. Что получается? `site-list__link`

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> -          <h2 class="visually-hidden">Предложения Кэт Энерджи</h2>
Не важно, скрытый или нет. Частью списка может быть быть только `<li>`.
Нельзя что-то поместить в список так, чтобы при этом оно почему-то не стало элементом списка.

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +          <li class="page-footer__item">
Как-то это странно. Смотри, у тебя же подразумевался раньше блок `social`.
Потому что очень логично выделить соцсети отдельным блоком.

А тут как-то странно. есть ссылки на соцсетки и называются они "элемент футера", "ссылка футера"...

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +          <svg class="page-footer__link-developer" aria-hidden="true" focusable="false"></svg>
Хочется все-таки выделения каких-то блоков в соответствии с макетом.
А то получается, что бахнула один блок "Футер", и все...

2021-11-30 21:57 UTC, wrgraff commented on source/index.html
> +          <svg class="page-footer__logo-image page-footer__logo" aria-hidden="true" focusable="false" width="128"
У тебя тут что-то странное.
Сперва идет элемент `page-footer__logo-image`.
В нем лежит одновременно элемент `page-footer__logo-image` (то есть — тот же самый элемент) и `page-footer__logo`.

Тут сразу 2 сомнительных решения:
1. Элемент находится сам в себе
2. Элемент смиксован с другим элементом того же блока — зачем?

Стилизовать это все будет ужасно неудобно, стили все время будут писаться туда, куда не надо

2021-12-01 19:48 UTC, Kris-js commented on source/index.html
> +      <img class="page-header__logo-image" src="" aria-hidden="true" width="33" height="38" alt="Кэт Энерджи">
Убрала

2021-12-01 19:48 UTC, Kris-js commented on source/index.html
> +<body class="page-body">
Вылезала ошибка в дереве

2021-12-01 19:59 UTC, Kris-js commented on source/index.html
> +          <li class="site-list__item site-list__item-active">
Случайно удалила второе тире)

2021-12-01 20:02 UTC, Kris-js commented on source/index.html
> +            <a class="site-list__item-link" href="#">Главная</a>
поставила ссылку

2021-12-01 20:02 UTC, Kris-js commented on source/index.html
> +            <a class="site-list__item-link" href="#">Каталог продукции</a>
Поставила

2021-12-01 20:05 UTC, Kris-js commented on source/index.html
> +            <a class="site-list__item-link" href="#">Подбор программы</a>
Уфф, исправила

2021-12-01 20:06 UTC, Kris-js commented on source/index.html
> -          <h2 class="visually-hidden">Предложения Кэт Энерджи</h2>
Поняла, спасибо!

2021-12-01 20:15 UTC, Kris-js commented on source/index.html
> +          <li class="page-footer__item">
сделала див social

2021-12-01 20:17 UTC, Kris-js commented on source/index.html
> +          <svg class="page-footer__link-developer" aria-hidden="true" focusable="false"></svg>
Согласна! Сделала блок copyright

2021-12-01 23:19 UTC, wrgraff commented on source/index.html
> +<body class="page-body">
Ты могла сделать и так: `<body class="page__body page-body">`

2021-12-01 23:20 UTC, wrgraff approved these changes

2021-12-01 23:20 UTC, wrgraff commented on source/index.html
> +            <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy"></a>
Вот это я понимаю

2021-12-01 23:20 UTC, wrgraff commented on source/index.html
> +            <a class="social__link social__link--instagram" href="https://www.instagram.com/htmlacademy"></a>
Текст бы еще внутрь для доступности

2021-12-01 23:20 UTC, merged

2021-12-02 20:10 UTC, Kris-js commented on source/index.html
> +            <a class="social__link social__link--instagram" href="https://www.instagram.com/htmlacademy"></a>
Есть вроде, перед ссылкой.

2021-12-02 20:10 UTC, Kris-js commented on source/index.html
> +<body class="page-body">
Сделала