Добавляет разметку внутренних страниц
htmlacademy-adaptive/1390101-cat-energy-24 pull request #4
Opened 2021-12-02 21:26 UTC by Kris-js

2021-12-03 18:38 UTC, wrgraff requested changes

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +            </a>
А почему выше у тебя пара `product__image-link` + `product__image`,
а здесь `product__title` + `product__card-title`?

Мне первый вариант больше нравится. Давай и второй по такой же схеме назовем?

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +            <d1 class="product__specifications">
У тебя написано `d1`. С цифрой. А это `dl` (от слов Definition List).
Как `ul` и `ol`, то есть это тоже список

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +              <a href="#" class="button product__button">заказать</a>
Не забудь закрыть список `<dl>`. И обязательно имей ввиду, что ссылка должна быть не внутри него

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +              <img class="product__image" src="" width="84" height="101" alt="1000gr">
Посмотри, [какие описания должны быть у картинок](https://weblind.ru/inner.html#image-content), чтобы незрячие хорошо их понимали.
Как думаешь, "1000gr" дает понимание что на картинке?

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +              <a href="#" class="button product__button">заказать</a>
Лучше писать в нормальном регистре
```suggestion
              <a href="#" class="button product__button">Заказать</a>
```

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +            <button class="button product__card-button" type="button">Показать все</button>
Кажется, вместо кнопки должна быть ссылка, а остальное — просто текст

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +          <button class="button additional__button" type="button">заказать</button>
На самом деле, на практике кнопки типа "Добавить в корзину" делают ссылками.

Потому что это для интернет-магазина критическая функциональность, и нужно подстраховаться и сделать так, чтобы кнопка работала без js.

Прямо в адрес ссылки может быть включен запрос с добавлением товара в корзину. При переходе на этот адрес товар добавляется в корзину и потом срабатывает переадресация обратно, где грузится страница с уже обновленной корзиной. Будет работать с перезагрузкой страницы, но зато будет работать всегда: ссылку в html-коде сломать крайне сложно.

А потом уже поверх пишется js, который останавливает переход по ссылке, сам вместо него делает запрос, получает ответ, а затем обновляет состояние корзины.

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +            молоко
Тут тоже хотелось бы обычных текстов, как мы пишем всегда

```suggestion
            Молоко
```

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +    <div class="present">
А нужна ли тут обертка?

2021-12-03 18:38 UTC, wrgraff commented on source/catalog.html
> +      <p class="present__description">Закажите все и получите чехол для кота в подарок!</p>
Мне кажется, что эта ремарка все-таки имеет отношение к предыдущей секции

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +      <div class="quaestionnaire">
Вот это слово! Хотя бы `questionary` взяла бы )
Все-таки, классы должны попроще называться, не так чтобы их только копированием можно было написать =)

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +              ИМЯ:*
Лучше писать в стандартном регистре
```suggestion
              Имя:*
```

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +          </p>
Чем поля вес, возраст и имя друг от друга отличаются визуально?
![изображение](https://user-images.githubusercontent.com/37917037/144653072-53378095-a30e-475a-9ee7-baf1d4b26fbd.png)

Да, там разная ширина, но она обусловлена размером текста.
В остальном оформление идентично. Хорошо бы под них выделить блок по этому поводу, но уж точно плохо создавать каждому тегу свой элемент

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +            <input class="quaestionnaire__age-cat" type="text" id="quaestionnaire-age-cat" name="quaestionnaire-age-cat"
Нейминг непонятный.
Как мне по имени элемента `quaestionnaire__age-cat` понять, что это инпут, а `quaestionnaire__age` — это лейбл?

Кроме того, в именовании вообще лучше не привязываться к смыслам. Мы стараемся быть как можно абстрактнее, потому что оформляем части интерфейса, а не смыслы

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +                    <span class="control-label">Похудение</span>
Почему инпут стал элементом блока `control`, а `control-mark` и `control-label` — нет?

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +                    <input class="visually-hidden control__input" type="radio" name="thick" value="thick">
Имена у чекбоксов одной группы должны быть идентичны. Иначе каждый из них выберется и на этом все. А нужно чтобы выбирался один из них

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +            <input class="field" placeholder="Расскажите обо всех повадках кота" type="comment" name="comment__box"
Это не инпут, а `<textarea>`.
Инпут не может быть многострочным

2021-12-03 18:38 UTC, wrgraff commented on source/form.html
> +            id="comment__box" required>
А где подпись для него?

2021-12-04 12:06 UTC, Kris-js commented on source/form.html
> +          <li class="site-list__item site-list__item--active">
исправила

2021-12-04 12:06 UTC, Kris-js commented on source/catalog.html
> +        <h2 class="visually-hidden">Карточки товара</h2>
Заменила

2021-12-04 12:21 UTC, Kris-js commented on source/catalog.html
> +      <h1 class="catalog__title">Каталог продукции</h1>
Сделала элементом `page-main`. Думала, что у секции должен быть заголовок с названием блока секции.

2021-12-04 13:00 UTC, Kris-js commented on source/catalog.html
> +            <d1 class="product__specifications">
А я думала почему он не закрывается) Можно было сделать не списком, а таблицей? Или такой список-нормальное решение?

2021-12-04 13:02 UTC, Kris-js commented on source/catalog.html
> +              <a href="#" class="button product__button">заказать</a>
Помню, в списке должны быть только элементы списка)

2021-12-04 14:23 UTC, Kris-js commented on source/catalog.html
> +          <li class="product__card">
Переделала

2021-12-04 14:31 UTC, Kris-js commented on source/catalog.html
> +          <li class="product__card">
на `product-card`, но мне почему-то не очень нравится

2021-12-04 14:31 UTC, Kris-js commented on source/catalog.html
> +            </a>
переделала

2021-12-04 14:55 UTC, Kris-js commented on source/catalog.html
> +              <img class="product__image" src="" width="84" height="101" alt="1000gr">
Хорошая статья! Исправила описания картинок

2021-12-04 20:05 UTC, Kris-js commented on source/catalog.html
> +              <a href="#" class="button product__button">заказать</a>
Поняла, исправила

2021-12-04 20:21 UTC, Kris-js commented on source/catalog.html
> +            <button class="button product__card-button" type="button">Показать все</button>
ой

2021-12-04 20:27 UTC, Kris-js commented on source/catalog.html
> +          <button class="button additional__button" type="button">заказать</button>
Поняла. Я почему-то в карточках товара догадалась сделать ссылками, а в доп. товарах кнопками)

2021-12-04 20:29 UTC, Kris-js commented on source/catalog.html
> +            молоко
ага, везде вроде поправила регистр

2021-12-04 20:32 UTC, Kris-js commented on source/catalog.html
> +    <div class="present">
Я сомневалась по поводу свг в виде подарка. Но потом поняла, что не нужно его вставлять в разметку, так как у него нет изменений по стайлгайду.

2021-12-04 20:33 UTC, Kris-js commented on source/catalog.html
> +      <p class="present__description">Закажите все и получите чехол для кота в подарок!</p>
согласна, перенесла

2021-12-04 20:36 UTC, Kris-js commented on source/form.html
> +      <div class="quaestionnaire">
Я старалась!)) Вместе с переводчиком гугл=))

2021-12-04 20:37 UTC, Kris-js commented on source/form.html
> +              ИМЯ:*
+

2021-12-04 23:10 UTC, wrgraff commented on source/catalog.html
> +      <h1 class="catalog__title">Каталог продукции</h1>
Элементы могут быть внутри вложенных блоков. Но обычно стоит такого избегать.
В данном случае заголовок первого уровня может быть перед `<section>`. То есть, получилась бы вот такая структура:

- header
  - nav
  - ...
- main
  - h1
  - section
    - h2
    - ...
  - section
    - h2
    - ...
  - section
    - h2
    - ...
- footer
  - ...

2021-12-04 23:12 UTC, wrgraff commented on source/catalog.html
> +      <h1 class="catalog__title">Каталог продукции</h1>
Заголовок первого уровня для страницы в целом.
Секшены же для отдельных блоков страницы, поэтому чаще заголовок первого уровня будет снаружи

2021-12-04 23:15 UTC, wrgraff commented on source/catalog.html
> +          <li class="product__card">
Почему не нравится?
`product__card` же нравился, чем `product-card` хуже?
Я только не понимаю, зачем было удалять класс элемента. Можно использовать миксование?

2021-12-04 23:21 UTC, wrgraff commented on source/catalog.html
> +          <li class="product-card">
Смотри, ты выделила блок `product-card`.
Но всё, что внутри него — осталось элементами блока `product`.

Добились ли мы того, чтобы `product-card` можно было использовать отдельно?
Нет, так как внутри остались элементы другого блока и без списка `product` все равно ничего не заработает.

2021-12-04 23:21 UTC, wrgraff commented on source/catalog.html
> +            <d1 class="product__specifications">
Как это не закрывается? Это тег с контентом из других тегов. В одинарные теги (как `<img>`, например) вложить ничего нельзя.
Таблица здесь не особо нужна, список определений лучше подходит

2021-12-04 23:35 UTC, wrgraff requested changes
Да, так сильно лучше, но нужно еще кое-что подправить

2021-12-04 23:35 UTC, wrgraff commented on source/catalog.html
>              <a class="product__card product__card--pagination-link" href="#">
Лучше убрать эту ссылку, достаточно и одной — которая в виде кнопки

2021-12-04 23:35 UTC, wrgraff commented on source/form.html
>            </p>
Что-то тут вот путаница какая-то:
https://github.com/htmlacademy-adaptive/1390101-cat-energy-24/blob/df822e70cdcfa406d3f528070c8bf014667386e9/source/form.html#L42-L49

Несколько вопросов сразу.
Зачем в параграфе скрытый текст? У нас же есть `<label>`.
Почему элемент `field__input` идет после блока `field`, а не внутри него?

Если у нас блок `field` включает в себя инпут и подпись, соединенные через id, то этим блоком должен быть параграф.
Если у нас блок `field` это лейбл, то в нем должен быть инпут внутри. Текст, возможно, нужно будет заключить в `<span>`, а параграф тогда не нужен

2021-12-04 23:35 UTC, wrgraff commented on source/form.html
> +              </label>
Зачем делать отметку и подпись внутри блока `radio` элементами блока `form-programm`?
Блок `radio` у тебя получается несамостоятельным из-за этого

2021-12-04 23:35 UTC, wrgraff commented on source/form.html
> +            <h2 class="form-group__title">Комментарий</h2>
Не надо `<h2>`, раз уж у нас нет больше в форме заголовков, а появились `<legend>`.
Пускай будет вообще обычный спан. А то он создает "помехи" в структуре заголовков =)

2021-12-05 05:34 UTC, Kris-js commented on source/catalog.html
> +      <h1 class="catalog__title">Каталог продукции</h1>
Все поняла, исправила

2021-12-05 05:41 UTC, Kris-js commented on source/catalog.html
> +          <li class="product-card">
Поняла, исправила

2021-12-05 06:05 UTC, Kris-js commented on source/catalog.html
>              <a class="product__card product__card--pagination-link" href="#">
убрала

2021-12-05 06:13 UTC, Kris-js commented on source/form.html
> +              </label>
исправила

2021-12-05 06:15 UTC, Kris-js commented on source/form.html
> +            <h2 class="form-group__title">Комментарий</h2>
поменяла на `span`

2021-12-05 11:29 UTC, wrgraff approved these changes

2021-12-05 11:29 UTC, merged