Добавляет стилизацию всех страниц
htmlacademy-adaptive/1390101-cat-energy-24 pull request #5
Opened 2021-12-10 21:11 UTC by Kris-js

2021-12-12 20:22 UTC, wrgraff requested changes

2021-12-12 20:22 UTC, wrgraff commented on source/sass/components/present-description.scss
> +  // background-image: ; чет ступор
Не понял )
В чем ступор то?

2021-12-12 20:22 UTC, wrgraff commented on source/sass/components/page-footer.scss
> +}
Элемент блока `copyright` не может находиться в файле блока `page-footer`

2021-12-12 20:25 UTC, Kris-js commented on source/catalog.html
> +      <p class="present-description">Закажите все и получите чехол для кота в подарок!</p>
Согласна, переделала

2021-12-12 20:30 UTC, Kris-js commented on source/sass/style.scss
> +@import "./components/form-options.scss";
Ок, исправила

2021-12-13 04:27 UTC, Kris-js commented on source/sass/global/global.scss
> +  src: url("/source/fonts/oswaldregular.woff2") format("woff2");
переделала

2021-12-13 04:27 UTC, Kris-js commented on source/sass/global/global.scss
> +}
сделала в отдельном

2021-12-13 04:34 UTC, Kris-js commented on source/sass/style.scss
> +@import "./components/slider.scss";
Ну вот, а я специально создавала, что-бы у всех блоков были отдельные файлы

2021-12-13 04:41 UTC, Kris-js commented on source/sass/style.scss
> +@import "./components/slider.scss";
поудаляла

2021-12-13 04:51 UTC, Kris-js commented on source/sass/global/global.scss
> +  src: url("/source/fonts/oswaldregular.woff2") format("woff2");
Но снова ничего не заработало. Нашла вот такую штуку в дискорте https://github.com/htmlacademy/yomoyo/issues/973, это решит проблему?

2021-12-13 18:40 UTC, Kris-js commented on source/sass/global/global.scss
> +Не могу найти шрифт Arial на сайте гугл фонтс
поняла

2021-12-13 18:51 UTC, Kris-js commented on source/sass/global/global.scss
> +  // font-family:"Oswald";
поставила Arial

2021-12-13 19:52 UTC, Kris-js commented on source/sass/components/product.scss
> +}
Ага, не заметила. Добавила в новый блок

2021-12-13 19:55 UTC, Kris-js commented on source/sass/components/page-footer.scss
> +}
убрала в блок copyright

2021-12-14 04:28 UTC, Kris-js commented on source/sass/global/global.scss
> +  src: url("/source/fonts/oswaldregular.woff2") format("woff2");
Все работает))

2021-12-14 05:20 UTC, Kris-js commented on source/sass/components/present-description.scss
> +  // background-image: ; чет ступор
все вставила, не поняла сначала как прописать путь

2021-12-14 20:29 UTC, wrgraff commented on source/sass/global/fonts.scss
> +}
Другие форматы файлов подключаются не так. Для этого не используется `@font-face`, они просто идут через запятую в свойстве `src`:

```css
    src:
        url('../fonts/open-sans-semibold.woff2') format('woff2'),
        url('../fonts/open-sans-semibold.woff') format('woff');
```

2021-12-14 20:29 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +  font-family: "Arial", sans-serif;
Не очень понятно зачем здесь прописывается `Arial`, ведь он должен наследоваться от body, разве нет?

2021-12-14 20:29 UTC, wrgraff commented on source/sass/global/global.scss
> +  src: url("/source/fonts/oswaldregular.woff2") format("woff2");
То, что предлагает Сергей, безусловно, помогло бы не спотыкаться об эту проблему, но это требует правок сборки.
Кроме того, я не уверен, что стоит это внедрять: кажется, то, что вы сталкиваетесь с этой проблемой, все же помогает лучше понять как работают пути и как работает сборка: например, осознать, что сама собой она пути не правил.

2021-12-14 20:37 UTC, Kris-js commented on source/sass/global/fonts.scss
> +}
исправила

2021-12-14 20:44 UTC, wrgraff requested changes
Совсем не используются переменные =(
Особого требования к их использованию конечно нет. Но надо бы хотя бы для себя их применить.

2021-12-14 20:45 UTC, Kris-js commented on source/sass/blocks/additional.scss
> +  font-family: "Arial", sans-serif;
Долго думала как сделать. Там текст прям в ссылке,  он Oswald. А остальное, что в ссылке (количество и цена) Arial.  Не стала текст ссылки в отдельный тег заворачивать, но пришлось ссылке задавать шрифт и переписать Ариал для количества и цены.

2021-12-14 20:46 UTC, Kris-js commented on source/sass/blocks/present.scss
> +  background-image: url(../img/background/present.png);
исправила

2021-12-14 20:46 UTC, wrgraff commented
Обрати внимание, проект не проходит тестирование:
![изображение](https://user-images.githubusercontent.com/37917037/146076565-ef9a7c33-682e-496e-abbd-c631590ebf08.png)

Ты так же можешь проверять это локально, запустив в терминале команду `npm test`

2021-12-14 20:59 UTC, Kris-js commented on source/sass/global/global.scss
> +  src: url("/source/fonts/oswaldregular.woff2") format("woff2");
Наверно) Вот не было бы этой проблемы, не задумалась бы даже об этом)

2021-12-16 23:58 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +  font-family: "Arial", sans-serif;
Так понятнее )

2021-12-17 00:02 UTC, wrgraff requested changes

2021-12-17 00:02 UTC, wrgraff commented on source/sass/global/fonts.scss
> +  src: url("../fonts/oswaldmedium.woff") format("woff");
Опять неправильно =(
Я же пишу, что через запятую пишутся форматы внутри свойства. А у тебя — 2 свойства.
И порядок не тот, первым должен идти современный формат. Важно соблюсти порядок подключения и начинать с более современного (менее поддерживаемого, но лучше оптимизированного) формата.

Браузер будет считывать список файлов по очереди и загрузит первый подходящий ему файл. Все браузеры, имеющие поддержку woff2, поддерживают и woff. Следовательно, если woff будет идти первым, то до более современного формата браузеры никогда не дойдут.

2021-12-17 00:02 UTC, wrgraff commented on source/sass/global/variables.scss
> +$color-black-900: #111111;
Почему это черный, а не темно-темно серый?

2021-12-17 00:02 UTC, wrgraff commented on source/sass/global/variables.scss
> +$color-black-1000: #000000;
У черного цвета градаций ведь быть не может. Или черный, или нет

2021-12-17 13:13 UTC, wrgraff reviewed
Вот теперь молодец )

2021-12-17 13:13 UTC, wrgraff approved these changes

2021-12-17 13:14 UTC, merged