Сетка для главной страницы
htmlacademy-adaptive/1390101-cat-energy-24 pull request #6
Opened 2021-12-24 11:00 UTC by Kris-js

2021-12-25 16:11 UTC, wrgraff requested changes

2021-12-25 16:11 UTC, wrgraff commented on source/sass/blocks/example.scss
> +// почему картинка не центрируется?
Потому что картинка находится в `<div>`'е.
В сетке участвуют только те элементы, которые вложены непосредственно в грид-элемент

2021-12-25 16:11 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +  display: grid;
А где же центрирование?

2021-12-25 16:11 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  flex-direction: column;
Непонятно зачем тут флекс

2021-12-25 16:11 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +// снова странности с центрированием
Какие странности?
Ты его центрировать пытаешься по вертикали. А там не в чем, ряд и так высотой со слайдер

2021-12-25 16:11 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +  align-self: center;
Лучше не писать стили размещения в грид-сетке для БЭМ-блоков.
Блок должен быть независим, а такой подходы связывает блок `example` и блок `slider`

2021-12-25 16:11 UTC, wrgraff commented on source/sass/blocks/social.scss
> +  grid-template-columns: 1fr 1fr 1fr;
Гриды любят известное заранее количество и размер колонок.
Если соцсетей станет 4, то колонки придется менять. Поэтому лучше подойдет флекс.

2021-12-25 16:11 UTC, wrgraff commented on source/sass/blocks/social.scss
> +// куда делись они??
У ссылок же нет никаких размеров

2021-12-26 19:12 UTC, Kris-js commented on source/sass/blocks/advantages.scss
> +почему-то включается только планшетная версия, как и в бенефитс
А десктопная версия? Прокомментировала, что-бы ты обратил внимание и подсказал что нужно поправить для того, что-бы заработало)

2021-12-26 19:15 UTC, Kris-js commented on source/sass/blocks/copyright.scss
> +  grid-template-columns: 115px 1fr;
поменяла)

2021-12-26 19:20 UTC, Kris-js commented on source/sass/blocks/social.scss
> +// куда делись они??
Задала, но они не появились

2021-12-27 05:20 UTC, Kris-js commented on source/sass/blocks/copyright.scss
> +  grid-column: 1 / 2;
убрала

2021-12-27 05:24 UTC, Kris-js commented on source/sass/blocks/copyright.scss
> +  display: grid;
переделала

2021-12-27 05:51 UTC, Kris-js commented on source/sass/blocks/advantages.scss
> +    column-gap: 154px;
![изображение](https://user-images.githubusercontent.com/84540806/147438925-ec73a168-dab0-4181-a79d-cfc4f68f8af6.png) А вот так? Или нужно смотреть именно по сетке?

2021-12-27 09:15 UTC, Kris-js commented on source/sass/blocks/advantages.scss
> +почему-то включается только планшетная версия, как и в бенефитс
Все поняла, зачем-то комментировала весь код, а не просто коммент)))

2021-12-27 10:20 UTC, Kris-js commented on source/sass/blocks/page-footer.scss
> +  display: grid;
добавила

2021-12-27 18:06 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +почему-то включается только планшетная версия, как и в бенефитс
Везде работает

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  width: 280px;
Так а дальше? На десктопе так и есть мобильная версия этого блока

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  width: 280px;
Усложняешь себе жизнь. Вот на мобильнике ты их отцентрировала отдельно.
А как будешь центрировать на десктопе? Там, где они должны стоять слева и справа друг от друга

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  width: 280px;
Тут тоже мобильник есть, а дальше?
Нужно планшет и десктоп сделать. Это не так и сложно. Кнопку — скрыть, а меню поставить в ряд с логотипом

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/map.scss
> +  width: 280px;
Где для планшета и десктопа версии?

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +  height: auto;
Это зачем?

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +  flex-direction: column;
Не совсем понятно для чего здесь флекс

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/slogan.scss
> +  width: 100%;
При таком сочетании разве будет хоть когда-то не 180 пикселей ширина?

2021-12-27 18:17 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +    column-gap: 154px;
Это всего лишь аутлайны элементов.
Не стоит полагаться на размеры элементов: нет никакой гарантии, что они в макете имеют какой-то смысл. Обрати внимание на свой скрин: там все блоки с цифрами по факту оказываются разной ширины.

Лучше смотри куда их вписывают, а не какого они размера

2021-12-27 18:20 UTC, wrgraff requested changes

2021-12-27 18:20 UTC, wrgraff commented on source/sass/blocks/social.scss
> +.social__link {
Ссылка по умолчанию — не блочный элемент!

2021-12-27 18:46 UTC, Kris-js commented on source/sass/blocks/page-header.scss
> +  flex-direction: column;
Не знаю.) Убрала

2021-12-27 18:53 UTC, Kris-js commented on source/sass/blocks/slider.scss
> +  align-self: center;
и они не работают, убрала

2021-12-27 19:01 UTC, Kris-js commented on source/sass/blocks/social.scss
> +.social__link {
исправила

2021-12-27 19:10 UTC, Kris-js commented on source/sass/blocks/slider.scss
> +// снова странности с центрированием
Убрала

2021-12-27 19:11 UTC, Kris-js commented on source/sass/blocks/social.scss
> +// куда делись они??
добавила `display: block`

2021-12-29 16:18 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    grid-template-columns: min-content 1fr;
min-content сожмет логотип, используй другой размер

2021-12-29 16:19 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    grid-column: 1 / 2;
Здесь ты ломаешь сетку внутри логотипа

2021-12-29 16:21 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    justify-content: flex-end;
Это должно быть у блока `.site-list`

2021-12-29 16:26 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    grid-column: 2 / 3;
Положение в гриде неверное

2021-12-29 16:26 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  grid-column: 2 / 4;
Положение в гриде неверное

2021-12-29 16:30 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  width: 280px;
На мобильном здесь не должно быть ограничения ширины

2021-12-29 16:30 UTC, wrgraff commented on source/sass/blocks/slogan.scss
> +
А на телефоне центрирование куда пропало?

2021-12-29 16:32 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +    margin-right: 50px;
?

2021-12-29 17:12 UTC, wrgraff requested changes

2021-12-29 17:12 UTC, wrgraff commented on source/sass/blocks/slogan.scss
> +  // Шрифт жирный
Непонятно, что ты хочешь этим сказать. Ты разве не знаешь как изменить толщину шрифта??

2021-12-31 17:22 UTC, wrgraff approved these changes

2021-12-31 17:23 UTC, wrgraff commented
Только проверяй код командой `npm test`. Тестирование так же на гитхабе проводится:
<img width="859" alt="изображение" src="https://user-images.githubusercontent.com/37917037/147833884-7e3680fb-c6a6-4cb4-aa99-779b31eaff16.png">

2021-12-31 17:23 UTC, merged