Добавляет сетку на внутренних страницах
htmlacademy-adaptive/1390101-cat-energy-24 pull request #7
Opened 2022-01-04 06:49 UTC by Kris-js

2022-01-05 13:41 UTC, wrgraff requested changes

2022-01-05 13:41 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +  // почему цвет текста не наследуется?
Все наследуется:

https://user-images.githubusercontent.com/37917037/148221751-8f14bf4a-0635-4768-81fe-82cf98528e69.mov

2022-01-05 13:41 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +.form-group--contacts {
Немного странно, что модификатор самого блока так далеко внизу.
Обычно модификаторы идут сразу за основным классом. А класс блока в файле обычно первый

2022-01-05 13:41 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +  display: flex;
Обрати внимание:
У тебя сам тип отображения задан через элемент блока `form-group`.
А поведение во флексе описано в элементе блока `field`:
https://github.com/htmlacademy-adaptive/1390101-cat-energy-24/blob/7fb55b302d0d401241ab5865fba77ad3d70ba0ec/source/sass/blocks/field.scss#L6

Это неудобно и сложно. Логичнее задать тип отображения в том же блоке `field`

2022-01-05 13:41 UTC, wrgraff commented on source/sass/blocks/form-options.scss
> +}
Тут тоже логично задавать поведение через блок `field`

2022-01-05 13:41 UTC, wrgraff commented on source/sass/blocks/present.scss
> +// голову сломала как поставить в десктопной версии вправо
Опять же, задача совершенно типичная. 2 блока стоят рядом.
Почему в одном месте ты это делаешь, а в другом вдруг не можешь?

И комментарий написан в странном месте. Положением этого блока в общей сетке управляет `additional`. Написав что-то внутри него его положение в родительской сетке не изменишь

2022-01-05 13:41 UTC, wrgraff commented on source/sass/blocks/product-card.scss
> +// пока не знаю как сделать нижний разделитель
Разделители — это декор

2022-01-05 13:41 UTC, wrgraff commented on source/sass/blocks/product.scss
> +  // не понимаю как выровнить в колонну
Вообще-то колонка — это по сути распределение элементов по умолчанию. Это должно навести на мысль о том, что ты сама в каком-то месте прописываешь ту сетку, которая сейчас работает.

Вообще, у тебя тут какая-то жуть. Сетка задается в блоке `product-card`, он переписывает то, что ты пишешь здесь, так как он подключен позже. Именно поэтому стоит ясно разделять что ив каком блоке определяется.
При чем, у тебя изначально был правильный подход — модификация блока `product-card`. Но ты зачем-то создала модификатор для элемента, которого не существует. Чем создала сразу 2 ошибки и нарушила логику БЭМ, что привело к проблемам со специфичностью.

Тебе нужно вернуться к модификации `product-card` или вообще сделать эту карточку другим блоком, потому что на карточку товара она не похожа и общего с ней ничего не имеет

2022-01-07 20:37 UTC, Kris-js commented on source/catalog.html
> +        <h1 class="product__title">Каталог продукции</h1>
Сделала так, не получалось выровнять.

2022-01-07 20:41 UTC, Kris-js commented on source/catalog.html
> +          <li class="product-card product__card--pagination">
Исправила

2022-01-07 20:43 UTC, Kris-js commented on source/catalog.html
> +      <a class="main-nav__logo">
добавила

2022-01-07 20:44 UTC, Kris-js commented on source/catalog.html
> +        </li>
Исправила

2022-01-07 20:44 UTC, Kris-js commented on source/form.html
> +        </li>
исправила

2022-01-08 18:39 UTC, Kris-js commented on source/sass/blocks/catalog.scss
> +  margin-right: 20px;
Убрала

2022-01-08 18:39 UTC, Kris-js commented on source/sass/blocks/catalog.scss
> +  display: grid;
Убрала

2022-01-08 18:49 UTC, Kris-js commented on source/sass/blocks/form-group.scss
> +  // почему цвет текста не наследуется?
Странно, сначала не наследовался. Но может из-за терминала, который ругался на другое правило.

2022-01-08 18:54 UTC, Kris-js commented on source/sass/blocks/form-group.scss
> +.form-group--contacts {
Поправила в соответствии с разметкой. Свойства в файлах не меняла)

2022-01-08 19:03 UTC, Kris-js commented on source/sass/blocks/present.scss
> +// голову сломала как поставить в десктопной версии вправо
Точно, он же родитель.

2022-01-08 19:18 UTC, Kris-js commented on source/sass/blocks/product-card.scss
> +// пока не знаю как сделать нижний разделитель
ок

2022-01-09 19:31 UTC, Kris-js commented on source/sass/blocks/field.scss
> +  width: 100%;
исправила

2022-01-09 19:31 UTC, Kris-js commented on source/sass/blocks/field.scss
> +  width: 100%;
width: 150px;

2022-01-10 18:09 UTC, Kris-js commented on source/sass/blocks/form-options.scss
> +}
сделала

2022-01-11 19:00 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +  // почему цвет текста не наследуется?
Если у тебя в терминале ошибка, то сборка не срабатывает и файл стилей, соответственно, не меняется

2022-01-11 19:10 UTC, wrgraff approved these changes
Молодец, хорошо поработала над ошибками.
Я приму задание, чтобы не мучиться с этим пул-реквестом больше, но есть пара небольших, но важных моментов. Обязательно поправь в следующем задании их!

2022-01-11 19:10 UTC, wrgraff commented on source/catalog.html
> +          <a class="site-list__link site-list__item--active" href="catalog.html">Каталог продукции</a>
Смотри внимательно: с какого элемента ты класс убираешь и на какой элемент добавляешь.
Сейчас у тебя ошибка по БЭМу получилась.

2022-01-11 19:10 UTC, wrgraff commented on source/catalog.html
> +          <a class="site-list__link site-list__item--active" href="catalog.html">Каталог продукции</a>
Адрес ссылки можно и удалить с активного пункта.
У тебя с этим как-то не понятно. На главной у логотипа ссылки на главную нет, а у пункта меню "главная" — есть.
Тебе нужно определиться: или ставить ссылки на текущую страницу, или убирать. И то и другое надо делать одинаково на всех страницах.

2022-01-11 19:10 UTC, wrgraff commented on source/catalog.html
> +            <a class="button product__button" href="#">Показать все</a>
Вообще, я думал, что это будет отдельный блок. Но и так уже лучше.

2022-01-11 19:10 UTC, wrgraff commented on source/form.html
> +            <p class="form-group__inner field">
Молодец, нашла и исправила проблему

2022-01-11 19:10 UTC, wrgraff commented on source/sass/blocks/catalog.scss
> -  margin-right: 20px;
Только добавь всей странице ограничение по ширине.
Где-то на уровне `<body>` нужно поставить минимально разрешенную ширину: 320 пикселей

2022-01-11 19:10 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +    flex-direction: column;
Так, а справа то от таблицы мы будем ставить блок с котом в сумке?

2022-01-11 19:11 UTC, merged

2022-01-12 11:13 UTC, Kris-js commented on source/catalog.html
> +          <a class="site-list__link site-list__item--active" href="catalog.html">Каталог продукции</a>
Ага невнимательность. Исправила

2022-01-12 11:13 UTC, Kris-js commented on source/catalog.html
> +          <a class="site-list__link site-list__item--active" href="catalog.html">Каталог продукции</a>
Удалила

2022-01-12 11:16 UTC, Kris-js commented on source/catalog.html
> +            <a class="button product__button" href="#">Показать все</a>
Ок, тогда оставлю. Все-таки может не плодить еще блоки. Суть поняла, спасибо!

2022-01-12 18:42 UTC, Kris-js commented on source/sass/blocks/catalog.scss
> -  margin-right: 20px;
сделала