Module5 task1
htmlacademy-adaptive/1390101-cat-energy-24 pull request #8
Opened 2022-01-14 18:57 UTC by Kris-js

2022-01-15 21:39 UTC, wrgraff requested changes

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/benefits.scss
> +.benefits__title--icons::before {
Что за странные модификаторы?
`benefits__title--icon` и `benefits__title--icons` — в одном одна иконка, в другом две?
Как вообще мне хоть примерно, не рассматривая страницу, по неймингу понять что именно происходит в этих модификаторах?

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/benefits.scss
> +  }
Аналогично списку преимуществ для этих модификаторов можно задать сперва общие стили.

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  background: url(../img/icon/example_decoration.svg);
Это не нужно реализовывать картинкой. Это же рамка вокруг псевдоэлемента.
Не забывай, что текст должен перекрывать рамку в соответствии со своим размером. А тут прерывание рамки в картинке. Это не годится.

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/example.scss
> +// как прибить совсем к краю?
Кого и куда прибить?
Если ты про это расположение текста, то тут ничего никуда не "прибито":
<img width="666" alt="изображение" src="https://user-images.githubusercontent.com/37917037/149637699-df22942d-49ff-4560-9c55-23ef2f2c13de.png">

Сумма стоит по центру блока "затрачено времени". Совсем другой эффект

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/example.scss
> +.example__image-be {
Что за `be`?
Это переводится как "быть".

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/example.scss
> +    top: 50%;
Не очень понимаю, что тут происходит, но это точно не соответствует макету:
<img width="641" alt="изображение" src="https://user-images.githubusercontent.com/37917037/149637801-febf6448-3ba1-4d32-a819-5c92a9233fff.png">

Смотри [мою демку](https://codepen.io/wrgraff/pen/eYGxZRq), пытайся повторить

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +// не стала прозрачной в активном состоянии почему?
`fade()` — функция из less, а не sass.

Не проще вообще всему элементу назначить прозрачность через `opacity`?

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    }
Ты просто скопировала решение из Барбершопа.
Там меню имеет странное решение: скрываются пункты кроме активного. У меню учебных проектов ничего подобного нет, здесь просто скрывается и показывается само меню целиком.
В результате закрытое меню у тебя сейчас выглядит будто его откусили:
<img width="699" alt="изображение" src="https://user-images.githubusercontent.com/37917037/149638058-902f9a9c-6bbe-4702-9da3-9a40cad3f68c.png">

Нужна другая реализация.

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/map.scss
> +// вот как прибивать текст в таких случаях br не поставишь же?
Почему бы и не поставить?

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/map.scss
А где вообще отступы то от плашки?
<img width="1289" alt="изображение" src="https://user-images.githubusercontent.com/37917037/149638093-3c89d9a8-5459-45d3-9345-b698da73c73d.png">

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +  // какая-то фигня с центровкой
Отступ стоять должен между пунктами списка. А у тебя он стоит внутри элементов у ссылок (что вообще не очень хорошо, так как рядом у нас не ссылки, а айтемы списка).

Я давно еще про это видео записывал, потому что очень уж много проблем было у тех, кто верстает футер. Там [разбор верстки Погнали](https://youtu.be/-YqNNlAMEbw), но я рассматриваю и отутспы и все то, что нужно и в твоем проекте.

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +  background-color: $color-grey-500;
Неожиданно. А где это на макете такой цвет у кнопок?
Они прозрачны должны быть. Не нужно им задавать цвет, аналогичный цвету фона под ними.
Прозрачность можно задать ключевым словом `transparent`.

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +// не работают кнопки, как сделать обводку вокруг кнопки?
Не понял вопроса. Какая у кнопок должна быть обводка?
У них есть самые обычные состояния. Наведение, нажатие. Их и надо сделать. Ты это умеешь.

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +.advantages__number {
А на мобильнике что делать с этими цифрами?
<img width="306" alt="изображение" src="https://user-images.githubusercontent.com/37917037/149638447-bfb2e80c-81c0-4d43-aa2d-f8ed7b098ecc.png">

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/slogan.scss
> +  background-image: url("../img/background/index-background__slogan.png");
Сделай лучше зеленого кота прямо на картинке.
Затем стоит взять с него цвет и нарисовать фон градиентом. Умеешь рисовать градиентом фоны?

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/slogan.scss
> +  background-image: url("../img/background/index-background__slogan.png");
Кстати, на большом экране половина блока должна стать зеленой. Это тоже нужно реализовать.

2022-01-15 21:39 UTC, wrgraff commented on source/sass/blocks/slogan.scss
>  }
А где вообще работа с `slogan__image`?
Она ведь адаптируется, меняет размеры: перемещается.
Да, саму картинку менять на разных экранах не нужно: это будет в лайве по графике. Но все остальные перемещения надо делать уже.

2022-01-15 21:40 UTC, wrgraff commented
Не забывай смотреть, проходит ли проект тестирование

2022-01-17 19:05 UTC, Kris-js commented on source/index.html
> +              </svg>
Удалила из разметки, добавила в фон ссылки

2022-01-17 19:08 UTC, Kris-js commented on source/index.html
> +                <span class="visually-hidden">Кнопка переключения</span>
Добавила

2022-01-17 19:09 UTC, Kris-js commented on source/sass/blocks/advantages.scss
> +  background: url(../img/icon/advantages_one.svg);
Исправила.

2022-01-17 19:10 UTC, Kris-js commented on source/sass/blocks/advantages.scss
> +  background: url(../img/icon/advantages_two.svg);
А я не понимала, почему он ругается, с путями мудрила) Добавила

2022-01-17 19:16 UTC, Kris-js commented on source/sass/blocks/advantages.scss
> +.advantages__description--three::before {
Круто! Исправила, сама не догадалась о таком решении. Спасибо)

2022-01-17 19:59 UTC, Kris-js commented on source/sass/blocks/benefits.scss
> +.benefits__title--icons::before {
Переименовала)

2022-01-17 20:03 UTC, Kris-js commented on source/sass/blocks/benefits.scss
> +  }
Задала

2022-01-18 08:57 UTC, Kris-js commented on source/sass/blocks/example.scss
> +  background: url(../img/icon/example_decoration.svg);
Переделала на рамку, только текст тоже перекрывается рамкой

2022-01-18 08:59 UTC, Kris-js commented on source/sass/blocks/example.scss
> +// как прибить совсем к краю?
Переделала, но сумму может обернуть в `span` и поставить по центру? Не совсем понимаю как ее отодвинуть.

2022-01-18 11:49 UTC, Kris-js commented on source/sass/blocks/slider.scss
> +  background-color: $color-grey-500;
поставила

2022-01-18 18:49 UTC, Kris-js commented on source/sass/blocks/advantages.scss
> +.advantages__number {
скрыла

2022-01-19 08:21 UTC, Kris-js commented on source/sass/blocks/example.scss
> +.example__image-be {
переименовала

2022-01-19 08:25 UTC, Kris-js commented on source/sass/blocks/map.scss
> +// вот как прибивать текст в таких случаях br не поставишь же?
А как тогда в других версиях? Выбрала пока другое решение, посмотри пожалуйста. Теперь думаю как сделать перенос через строку

2022-01-20 19:03 UTC, wrgraff commented on source/sass/blocks/example.scss
>  .example__description-text {
А чтобы рамка текст не перекрывала, можно тексту фон задать в цвет фона блока...

2022-01-20 19:03 UTC, wrgraff commented on source/sass/blocks/example.scss
> +// как прибить совсем к краю?
Да, видимо именно так и придется отодвинуть

2022-01-20 19:12 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  grid-template-columns: var(--active-position, 50%) 1fr;
Не, тебе не нужен `var()`, это у меня для реализации интерактивности: чтобы слайдер работал. А ты только процент оставь )

2022-01-20 19:12 UTC, wrgraff commented on source/sass/blocks/example.scss
> +  border-radius: 8px;
Не копируй весь код, вот зачем тебе радиус тут? )

2022-01-20 19:12 UTC, wrgraff commented on source/sass/blocks/example.scss
> +.example__image--next {
Ты не посмотрела в код: почему картинки не уменьшаются и не обрезаются?
Потому что у тебя глобально задана максимальная ширина. Для этих двух картинок ее надо сбросить.

2022-01-20 19:12 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    }
Хм, не поправила

2022-01-20 19:13 UTC, wrgraff commented on source/sass/blocks/map.scss
> +// вот как прибивать текст в таких случаях br не поставишь же?
Лучше оставить это на сверку макета по ПП, сейчас это все-таки мелочи

2022-01-20 19:15 UTC, wrgraff commented on source/sass/blocks/slogan.scss
> +  background-image: url("../img/background/index-background__slogan.png");
Тут нам надо с градиентами поработать, чтобы решить задачу

2022-01-20 19:16 UTC, wrgraff approved these changes

2022-01-20 19:16 UTC, merged